name: First workflow
on:
    push:
        branches:
            - dev
            - main
    pull_request: 
        branches:
            - dev
    workflow_dispatch:
jobs:
    build:
        runs-on: self-hosted
        steps:
            - run: |
                echo "Hello World"
                ls 
              name: Starting
    checkout:
        runs-on: self-hosted
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - run: ls
    Test:
        needs: build
        environment: dev
        runs-on: self-hosted
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - run: ls
    Deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - run: mkdir tarik
    checkout2:
        runs-on: self-hosted
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - run: ls
    Test2:
        runs-on: self-hosted
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - run: ls
    Deploy2:
        runs-on: self-hosted
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - run: mkdir tarik
              
              
