name: Get The Artifact

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Create an exec file
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py
        ls

    - name: Get the exec file
      uses: actions/upload-artifact@v7
      with:
        name: my_exec_file
        path: dist
          
      
